# Generated by Django 5.2.8 on 2025-11-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_end_time_quiz_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='start_time',
        ),
    ]