# Generated by Django 5.2.8 on 2025-11-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quiz_end_time_remove_quiz_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='question_order',
            field=models.TextField(blank=True, null=True),
        ),
    ]
